##name: Deploy to Railway

#on:
 # push:
   # branches: [ main ]
###
#jobs:
 # helloworld:
  #  runs-on: ubuntu-latest
#
 #   steps:
 #     - uses: actions/checkout@v4
#
  #    - name: Imprimir en consola
 #       run: echo "Hello World, GITHUB ACTIONS"
##

name: Deploy to Railway

on:
  push:
    branches: [ master ]

jobs:
  helloworld:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Imprimir en consola
        run: echo "Hello World, GITHUB ACTIONS"


  test:
    needs: helloworld
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.text

      - name: Test FastAPI imports
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          python -c "from main import app; print("FASTAPI app ")"

      - name: Run tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        run: |
          pytest --fixtures test_database.py